# Header
menu:
  首页: / || fas fa-home
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清單||fa fa-heartbeat:
    - 书籍 || /book/ || fas fa-music
    - 美食 || /Gallery/ || fas fa-images
    - 电影 || /movies/ || fas fa-video
  友联: /link/ || fas fa-link

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 代码高亮
highlight_theme: mac light
# 代码复制支持
highlight_copy: true
#代码框不可展开，需点击'>'打开
highlight_shrink: false
# 代码换行
code_word_wrap: true

# 头像
avatar:
  img: https://cdn.pixabay.com/photo/2020/12/27/12/07/sunrise-5863751_1280.png
  effect: false # 頭像會一直轉圈

# 顶部图
index_img: https://cdn.pixabay.com/photo/2021/01/05/06/40/boat-5889919_1280.png


# 社交图片
CDN_USE:
  css:
    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://use.fontawesome.com/releases/v5.8.1/css/all.css

social:
  fab fa-github: https://github.com/liangyuanjin || Github
  fas fa-envelope: https://mail.163.com/ || Email

# 相关文章
related_post:
  enable: true
  limit: 6 #显示推荐文章数目

# 博客年份
since: 2018

# 个人信息位置
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: left # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
    text: Github
    link: https://github.com/jerryc127/hexo-theme-butterfly
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true


busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 自定义主题色
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"

# 彩条
canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false  #設置是否每次點擊都更換綵帶
  mobile: false # false 手機端不顯示 true 手機端顯示


# 主頁subtitle
subtitle:
  enable: true
  # 打字效果
  effect: true
  # 循環或者只打字一次
  loop: false
  source: false
  sub:
    - 世界上任何书籍都不能带给你好运,但它们都让你悄悄成为你自己 —— 赫尔曼.黑塞
    - 有事做有所期待，日子就是幸福的

#  搜索
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Gitalk
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: true # Display comment count in Home Page

gitalk:
  client_id: e2bb75006d5c67aba0ff
  client_secret: e3cc4b3162384df1c0d28202856a9e0631ef880b
  repo: wuchang
  owner: liangyuanjin
  admin: liangyuanjin
  language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru
  perPage: 10 # Pagination size, with maximum 100.
  distractionFreeMode: false # Facebook-like distraction free mode.
  pagerDirection: last # Comment sorting direction, available values are last and first.
  createIssueManually: false # Gitalk will create a corresponding github issue for your every single page automatically

footer:
  owner:
    enable: true
    since: 2018
  footer_bg: true
