# Header
menu:
  首页: / || fas fa-home
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友联: /link/ || fas fa-link

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 代码高亮
highlight_theme: light
# 代码复制支持
highlight_copy: true
#代码框不可展开，需点击'>'打开
highlight_shrink: true
# 代码换行
code_word_wrap: true

avatar:
  img: /img/avatar.jpeg
  effect: false # 頭像會一直轉圈

index_img: /img/banner.JPG

# 社交图片
CDN_USE:
  css:
    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://use.fontawesome.com/releases/v5.8.1/css/all.css
